# @hostname = http://127.0.0.1:8000
@hostname = http://192.168.31.138:8000
@session_id = c58dcf27-faa9-43cf-b007-f752f4c4e001

###
GET {{hostname}}/health

###
POST {{hostname}}/chat/{{session_id}}

{
  "message": "Расскажи про себя и свою команду."
}

@token=7801364399:AAGyaOWH4YvYE8dDh88lB2awJTZkdYRFTRs


###
POST https://api.telegram.org/bot{{token}}/sendMessage
Content-Type: application/json

{"chat_id": 229147236, "text": "asdasdasdasdasd"}
