@hostname = http://192.168.31.240:8001

@api_key = sk-d00b792327b44da6876a1419e059ee99

@model = neuralmagic/Qwen2-1.5B-Instruct-quantized.w8a16


###
GET {{hostname}}/docs


###
POST {{hostname}}/v1/chat/completions
Authorization: Bearer {{api_key}}
Content-type: application/json

{
  "model": "{{model}}",
  "messages": [
      {
          "role": "user",
          "content": "Write a one-sentence bedtime story about a unicorn."
      }
  ]
}
