name: Close inactive issues
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 5
          days-before-issue-close: 0
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 5 days with no activity. If you want to keep this issue active, please leave a comment. A comment will reset the inactivity timer and prevent the issue from being closed."
          close-issue-message: "This issue was closed due to inactivity. If you still need assistance, feel free to reopen the issue or create a new one with updated information."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
